name: Electron Build

permissions:
  contents: read
  packages: write
  actions: read

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        arch: [x64, arm64]
        include:
          - os: windows-latest
            arch: x64
          - os: windows-latest
            arch: ia32
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        
    - name: Set up build tools (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install pkg-config
      
    - name: Set up build tools (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        npm install --global vsce
        choco install visualstudio2022-workload-vctools --confirm
        
    - name: Install dependencies
      run: npm install
      
    - name: Configure node-gyp for Electron
      run: npm run build-electron
      env:
        ELECTRON_VERSION: v22.3.13
      
    - name: Rebuild for Electron
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" && "${{ matrix.arch }}" == "ia32" ]]; then
          npm run build-ia32
        else
          electron-rebuild --version v22.3.13 --dist-url https://npm.taobao.org/mirrors/electron --arch=${{ matrix.arch }}
        fi
      env:
        ELECTRON_VERSION: v22.3.13
      
    - name: Run tests
      run: npm test
      
    - name: Package Electron build artifacts
      shell: bash
      run: |
        mkdir -p dist/electron-${{ matrix.os }}
        cp -r build/Release/binding.node dist/electron-${{ matrix.os }}/
        tar -czvf electron-build-${{ matrix.os }}-${{ matrix.arch }}.tar.gz -C dist/electron-${{ matrix.os }} .
        
    - name: Upload Electron build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: electron-build-${{ matrix.os }}-${{ matrix.arch }}
        path: electron-build-${{ matrix.os }}-${{ matrix.arch }}.tar.gz