name: Electron Build

permissions:
  contents: read
  packages: write
  actions: read

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        
    - name: Set up build tools (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install pkg-config
      
    - name: Set up build tools (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        npm install --global windows-build-tools
        
    - name: Install dependencies
      run: npm install
      
    - name: Configure node-gyp for Electron
      run: npm run configure
      env:
        ELECTRON_VERSION: v22.3.13
      
    - name: Rebuild for Electron
      run: npm run build-electron
      env:
        ELECTRON_VERSION: v22.3.13
      
    - name: Run tests
      run: npm test
      
    - name: Package Electron build artifacts
      shell: bash
      run: |
        mkdir -p dist/electron-${{ matrix.os }}
        cp -r lib/ build/ dist/electron-${{ matrix.os }}/
        tar -czvf electron-build-${{ matrix.os }}.tar.gz -C dist/electron-${{ matrix.os }} .
        
    - name: Upload Electron build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: electron-build-${{ matrix.os }}
        path: electron-build-${{ matrix.os }}.tar.gz