name: Create Release

on:
  workflow_run:
    workflows: ["Node Build", "Electron Build"]
    types:
      - completed

jobs:
  create-release:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.name == 'Node Build' || github.event.workflow_run.name == 'Electron Build')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set environment variables
      run: |
        echo "NODE_VERSION=16.17.1" >> $GITHUB_ENV
        echo "ELECTRON_VERSION=22.3.13" >> $GITHUB_ENV
      
    - name: Get version
      id: version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
    - name: Download and extract Node builds
      shell: bash
      run: |
        mkdir -p artifacts/node-builds
        gh release download ${{ github.ref_name }} --pattern "node-build-*-${{ env.NODE_VERSION }}-*.tar.gz" --dir artifacts/node-builds
        find artifacts/node-builds -name "*.tar.gz" -exec tar -xzvf {} -C artifacts/node-builds \;
      
    - name: Download and extract Electron builds
      shell: bash
      run: |
        mkdir -p artifacts/electron-builds
        gh release download ${{ github.ref_name }} --pattern "electron-build-*-${{ env.ELECTRON_VERSION }}-*.tar.gz" --dir artifacts/electron-builds
        find artifacts/electron-builds -name "*.tar.gz" -exec tar -xzvf {} -C artifacts/electron-builds \;
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: Release v${{ steps.version.outputs.version }}
        body: |
          Multi-platform build for Node.js v${{ env.NODE_VERSION }} and Electron v${{ env.ELECTRON_VERSION }}
          
          **Supported Architectures:**
          - macOS: x64 (Intel), arm64 (Apple Silicon)
          - Windows: x64 (64-bit), ia32 (32-bit)
          
          **Build Artifacts:**
          - node-build-<os>-<arch>-${{ env.NODE_VERSION }}.tar.gz
          - electron-build-<os>-<arch>-${{ env.ELECTRON_VERSION }}.tar.gz
        draft: false
        prerelease: false
        files: |
          artifacts/node-builds/**
          artifacts/electron-builds/**